name = "TrainingPhantoms"
uuid = "cd4f3286-b756-4d71-b99f-a4358d548556"
authors = ["Tobias Knopp <tobias.knopp@tuhh.de> and contributors"]
version = "0.1.0"

[deps]
ImagePhantoms = "71a99df6-f52c-4da1-bd2a-69d6f37f3252"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
ImagePhantoms = "0.6"
StableRNGs = "1.0"
ImageFiltering = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
